apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 2  # Increase replicas for high availability
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/your-frontend-image:latest  # Replace with your actual image
        command: ["npx", "run", "frontend"]
        ports:
        - containerPort: 3000
        env:  # Optional: Add environment variables if needed
        - name: NODE_ENV
          value: "production"
        resources:  # Optional: Add resource constraints
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:  # Optional: Add liveness probe
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:  # Optional: Add readiness probe
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: my-app
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  # Port exposed externally
    targetPort: 3000  # Port on the container
  type: LoadBalancer  # Exposes the service externally

