apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: my-app
spec:
  selector:
    app: qdrant
  ports:
  - protocol: TCP
    port: 6333
    targetPort: 6333
